version: '2.2'
services:
  go-pttbbs:
    image: pttofficialapps/go-pttbbs:latest
    # image: go-pttbbs:main
    ports:
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:48763:48763"
      - "127.0.0.1:3458:3456"
    restart: always
    volumes:
      - ${BBSHOME}:/home/bbs
    networks: 
      - bbs
  mongo:
    image: mongo:4.4.2
    restart: always
    volumes:
      - ${MONGO}:/data
      - ${MONGO}/db:/data/db
      - ${MONGO}/configdb:/data/configdb
    cpus: ${MONGO_CPU}
    mem_limit: ${MONGO_MEM}
    mem_reservation: ${MONGO_MEM}
    ports:
       - "27017:27017"
    networks: 
      - bbs
  redis:
    image: redis:6.0.9-alpine
    restart: always
    ports:
       - "6379:6379"
    networks: 
      - bbs
  postfix:
    image: chhsiao1981/docker-postfix
    volumes:
      - ${POSTFIX_MAIN_CF}:/etc/postfix/main.cf
      - ${POSTFIX_MASTER_CF}:/etc/postfix/master.cf
    restart: always
    ports:
       - "587:587"
    networks: 
      - bbs

networks: 
  bbs:
        driver: bridge
        ipam:
            config:
                - subnet: 172.251.112.0/24
                  gateway: 172.251.112.1
              
